### ISSUE TITLE
Tips for getting query_hash

### ISSUE THREAD

**Issue by bondobrus** [TufayelLUS/Instagram-Reels-Downloader-Scripts#2]
In the https://github.com/TufayelLUS/Instagram-Reels-Downloader-Scripts/blob/main/reels.php query_hash is `b3055c01b4b222b8a47dc12b090e4e64` I wonder how where is that query_hash on instagram? How to find it on instagram. Any tips would be very useful.

**Comment by TufayelLUS** [comment]
It used to be there on instagram network log when I created this project. Instagram might have updated their API again for which you may not see it now.

**Comment by bondobrus** [comment]
> It used to be there on instagram network log when I created this project. Instagram might have updated their API again for which you may not see it now.

Instagram recently does a lot of changes with their API which I fully don't understand at the moment. I've found articles in the past that says `query_hash` was available in network tab in Fetch/XHR filter. Few artciles also says it was available in their bundles as a part of minified/obfuscated values https://www.instagram.com/static/bundles/base/Consumer.js/6945672b0d17.js

However I can't find it in network tab. Does they completetly disabled it to be not available for public?

**Comment by TufayelLUS** [comment]
> > It used to be there on instagram network log when I created this project. Instagram might have updated their API again for which you may not see it now.
> 
> Instagram recently does a lot of changes with their API which I fully don't understand at the moment. I've found articles in the past that says `query_hash` was available in network tab in Fetch/XHR filter. Few artciles also says it was available in their bundles as a part of minified/obfuscated values https://www.instagram.com/static/bundles/base/Consumer.js/6945672b0d17.js
> 
> However I can't find it in network tab. Does they completetly disabled it to be not available for public?

As this is a very popular social media website, their developers are actively working on different things to make user experience better and also prevent unwanted misuse of their API endpoints. So, it's very much unpredictable what they're going through and what they'll come up with as the time progresses.
